### ISSUE TITLE
Servercloner doesnt clone voice channels

### ISSUE THREAD

**Issue by Gexploit** [GhostSelfbot/Ghost#34]

**Comment by shibakek2** [comment]
well i have a paid self bot. its a rework of this along with some added custom commands. 
https://shibabotselfbot.ga/

**Comment by timof121** [comment]
> well i have a paid self bot. its a rework of this along with some added custom commands. https://shibabotselfbot.ga/

ur selling ghost fork? sus

**Comment by abashir7866** [comment]
1. You need to skid to make a selfbot?
2. Ghost code is shit. Even benny says so.

**Comment by shibakek2** [comment]
> 

Sure there code is not the best nor up to date. But my project is to simply to pass time and make something way better than this. For one abashir i am not skidding. i am not copying all there code renaming there stuff and selling ghosts sc. i am adding a lot of custom commands. added HWID lock. made a free version all because of opensource things. this is not skidding. its being resourceful.

**Comment by shibakek2** [comment]
> r selling ghos

We do plan on it someday soon yes. But for now we are still in development. We have a lot to tackle in  the future with more updates. we have already got rid of discord.py and are using a fork. i wouldn't say its sus when I've slaved weeks into this project. We don't log tokens like executer. we only log HWID to keep track of purchases when they become available shortly! 
  
Speeking of. If you would like to try er out i can whitelist you so you can use it and maybe gain some trust here.

**Comment by abashir7866** [comment]
> Speeking of. If you would like to try er out i can whitelist you so you can use it and maybe gain some trust here. 

sure ill take a whitelist kek

**Comment by bentettmar** [comment]
@shibakek2 do you at least have ghost's license in your project src somewhere?
